config/routes.rb
Invoices::Application.routes.draw do
  controller :sessions do
    get "login", :action => :new, :as => :show_login
    post "login", :action => :create, :as => :do_login
    delete "logout", :action => :destroy, :as => :logout
  end

  resources :invoices
  
  resources :clients

  resources :companies

  resources :users
  controller :users do
    get "sign_up", :action => :sign_up, :as => :sign_up
    post "sign_up", :action => :public_create, :as => :public_user_create
  end

  root :to => "sessions#new"

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  # TODO: Add tax info to invoice
  
  validates :client_id, :presence => true
  validates :status, :inclusion => { :in => ['draft', 'sent', 'paid'] }
  
  #validate :at_least_one_item
  
  belongs_to :client
  has_many :items, :dependent => :destroy
  accepts_nested_attributes_for :items, :allow_destroy => true
  
  def at_least_one_item
    self.errors.add(:items, "Invoice should have at least one item.") if self.items.empty?
  end
  
  def total  
    @total = 0
    self.items.each do |item|
      @total += item.total_price
    end
    
    @total
  end
  
  def validate_client_belongs_to(user)
    unless user.company.clients.find(self.client_id)
      self.errors.add(:client_id, "is invalid.") 
      false
    else
      true
    end
  rescue ActiveRecord::RecordNotFound
    self.errors.add(:client_id, "is invalid.") 
    false
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  # GET /invoices
  # GET /invoices.xml
  def index
    #@invoices = Invoice.all
    @invoices = Invoice.where('client_id in (?)', current_user.company.clients.all.collect(&:id)) \
                       .paginate(:page => params[:page], :per_page => 10, :order => 'created_at desc')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @invoices }
    end
  end

  # GET /invoices/1
  # GET /invoices/1.xml
  def show
    @invoice = Invoice.where('id = ? and client_id in (?)', params[:id], current_user.company.clients.all.collect(&:id)).first
    
    not_found and return unless @invoice
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @invoice }
      format.pdf { render :layout => false }
    end
  end

  # GET /invoices/new
  # GET /invoices/new.xml
  def new
    @invoice = Invoice.new
    @item = Item.new # Fix for error list, which throws exception if item is nil

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @invoice }
    end
  end

  # GET /invoices/1/edit
  def edit
    @invoice = Invoice.where('id = ? and client_id in (?)', params[:id], current_user.company.clients.all.collect(&:id)).first
    not_found and return unless @invoice
  end

  # POST /invoices
  # POST /invoices.xml
  def create
    @invoice = Invoice.new(params[:invoice])
    
    respond_to do |format|
      if @invoice.validate_client_belongs_to(current_user) and @invoice.save
        format.html { redirect_to(@invoice, :notice => t('.invoice_created')) }
        format.xml  { render :xml => @invoice, :status => :created, :location => @invoice }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @invoice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /invoices/1
  # PUT /invoices/1.xml
  def update
    @invoice = Invoice.where('id = ? and client_id in (?)', params[:id], current_user.company.clients.all.collect(&:id)).first
    
    not_found and return unless @invoice

    respond_to do |format|
      if @invoice.validate_client_belongs_to(current_user) and @invoice.update_attributes(params[:invoice])
        format.html { redirect_to(@invoice, :notice => t('.invoice_updated')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @invoice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.xml
  def destroy
    @invoice = Invoice.where('id = ? and client_id in (?)', params[:id], current_user.company.clients.all.collect(&:id)).first
    not_found and return unless @invoice
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to(invoices_url, :notice => t('.invoice_deleted')) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.haml
= form_for @invoice do |f|
  -# Form errors
  - if @invoice.errors.any?
    %div#error_explanation.grid_16
      - @invoice.errors.full_messages.each do |msg|
        %p.error= msg
  
  -# Client selection
  .grid_8
    = f.label :client_id, t('.client_html')
    %br
    = f.select :client_id, options_from_collection_for_select(current_user.company.clients, :id, :name), :prompt => t('.select')
  
  -# Invoice status
  .grid_8
    = f.label :status, t('.status_html')
    %br
    = f.select :status, ['draft', 'sent', 'paid'].collect { |s| [t('.'+s), s] }
  
  = render :partial => "shared/separator"
  
  -# Items
  .grid_16
    %label= t('.items')
    %table#items_table
      %thead
        %tr
          %th= t('.quantity')
          %th= t('.description')
          %th= t('.unit_cost')
          %th= t('.discount')
          %th= t('.total')
          %th &nbsp;
      %tfoot
        %tr
          %td{:colspan => 6}
            %button#add_item= t('.add_item')
      %tbody
        - @invoice.items << Item.new(:quantity => 0, :unit_cost => 0, :discount => 0) if @invoice.new_record? and @invoice.items.empty?
        - @invoice.items.each do |item|
          = f.fields_for :items, item do |ff|
            = render item, :ff => ff, :new_record => @invoice.new_record?
  
  = render :partial => "shared/separator"
    
  -# Terms
  .grid_16
    = f.label :terms, t('.terms_html')
    %br
    = f.text_area :terms, :rows => 2
  
  = render :partial => "shared/separator"
  
  -# Notes
  .grid_16
    = f.label :notes, t('.notes_html')
    %br
    = f.text_area :notes, :rows => 2
    
  = render :partial => "shared/separator"
  
  -# Submission
  .grid_16
    = f.submit t('.save_invoice')
    = link_to t('.cancel'), invoices_path, :confirm => t('.confirm_cancel')
  
  -# jQuery Template for items
  %script#item_template{:type => "text/x-jquery-tmpl"}
    = render Item.new, :new_record => @invoice.new_record?
  
  -# Utility jQuery
  :javascript
    $(function(){
      function get_new_index() {
        if ($('table#items_table tbody tr:last td:first input').length == 0) {
          return 0;
        }
        else {
          return parseInt($('table#items_table tbody tr:last td:first input').attr('name').match(/\d+/)[0]) + 1;
        }
      }
    
      $('#add_item').click(function(){
        $('#item_template').tmpl({index: get_new_index()}).appendTo('table#items_table tbody');
        return false;
      });
    
      $('.delete_item').live('click', function(){
        var context = $(this).parent().parent()
        if ($('input[name*=_destroy]', context).length == 0) {
          context.remove(); // If its a new item then simply remove it from the dom
        }
        else {
          context.hide();
          $('input[name*=_destroy]', context).val('true'); // This will tell the server to delete the record
        }
      });
    
      // Update totals
    
      function update_price(elem) {
        var context = $(elem).parent().parent()[0].tagName == 'TD' ? $(elem).parent().parent().parent() : $(elem).parent().parent();
        var quantity = $('.quantity-input', context).val();
        var unit_cost = $('.unit_cost-input', context).val();
        var discount = $('.discount-input', context).val();
      
        // Check they're numbers
        quantity = isNaN(quantity) ? 0 : quantity;
        unit_cost = isNaN(unit_cost) ? 0 : unit_cost;
        discount = isNaN(discount) ? 0 : discount;
      
        // Update
        $('.total-price', context).html('$ ' + (quantity * unit_cost * (1 - (discount / 100.0))));
      }
    
      $('.quantity-input').live('keyup', function(){ update_price(this); });
      $('.unit_cost-input').live('keyup', function(){ update_price(this); });
      $('.discount-input').live('keyup', function(){ update_price(this); });
    });

app/views/invoices/_static_item.html.haml
%tr
  %td.align-right= item.quantity
  %td&= item.description
  %td.align-right= number_to_currency(item.unit_cost)
  %td.align-right= item.discount.to_s + "%"
  %td.align-right= number_to_currency item.total_price

app/views/invoices/edit.html.haml
.grid_16
  %h1= t('.edit_invoice')

= render 'form'

app/views/invoices/index.html.haml
%h1
  = t('.list_invoices')
  %span.right= link_to t('.new_invoice'), new_invoice_path

%table
  %thead
    %tr
      %th= t('.id')
      %th= t('.client')
      %th= t('.status')
      %th= t('.amount')
      %th= t('.date_created')
      %th= t('.actions')
  %tfoot
    %tr
      %td{:colspan => 6}= will_paginate @invoices
  %tbody
    -@invoices.each do |invoice|
      %tr
        %td{:ckass => "align-right"}= invoice.id
        %td
          = invoice.client.name
          - unless invoice.client.email.empty?
            \/
            = mail_to invoice.client.email, 'Email'
        %td{:class => "invoice-status invoice-status-#{invoice.status}"}= t('.' + invoice.status)
        %td{:class => "align-right"}= number_to_currency(invoice.total)
        %td= l(invoice.created_at, :format => :short)
        %td
          = link_to t('.show'), invoice
          = link_to t('.pdf'), invoice_path(invoice, :format => :pdf), :target => '_blank'
          = link_to t('.edit'), edit_invoice_path(invoice)
          = link_to t('.destroy'), invoice, :confirm => t('.confirm_delete'), :method => :delete

app/views/invoices/new.html.haml
.grid_16
  %h1= t('.create_invoice')

= render 'form'

app/views/invoices/show.html.haml
.grid_16
  %h1
    = t('.invoice') + " #" + @invoice.id.to_s

.grid_8
  = label_tag t('.client')
  = @invoice.client.name
  %br
  = @invoice.client.company_name
  %br
  = @invoice.client.address

.grid_8
  = label_tag t('.status')
  %span{:class => "invoice-status invoice-status-#{@invoice.status}"}= t('.' + @invoice.status) 

= render :partial => "shared/separator"

.grid_16
  %label= t('.items')
  %table#items_table
    %thead
      %tr
        %th{:width => 40}=  t('.quantity')
        %th{:width => 410}= t('.description')
        %th{:width => 85}=  t('.unit_cost')
        %th{:width => 40}=  t('.discount')
        %th=                t('.total')
    %tfoot
      %tr
        %td.align-right.invoice-total{:colspan => 6}
          %strong
            = t('.total')
            = number_to_currency(@invoice.total)
    %tbody
      - @invoice.items.each do |item|
        = render :partial => "static_item", :locals => {:item => item}

= render :partial => "shared/separator"

.grid_16
  = label_tag t('.terms')
  %br
  &= @invoice.terms
  
= render :partial => "shared/separator"

.grid_16
  = label_tag t('.notes')
  %br
  &= @invoice.notes
  
= render :partial => "shared/separator"

.grid_2
  = button_to t('.send'), '#' if @invoice.status == 'draft'
.grid_2
  = button_to t('.view_pdf'), invoice_path(@invoice, :format => :pdf), :method => :get
.grid_4
  = button_to t('.invoices'), invoices_path, :method => :get