config/routes.rb
Invoices::Application.routes.draw do
  controller :sessions do
    get "login", :action => :new, :as => :show_login
    post "login", :action => :create, :as => :do_login
    delete "logout", :action => :destroy, :as => :logout
  end

  resources :invoices
  
  resources :clients

  resources :companies

  resources :users
  controller :users do
    get "sign_up", :action => :sign_up, :as => :sign_up
    post "sign_up", :action => :public_create, :as => :public_user_create
  end

  root :to => "sessions#new"

end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  validates :email, :uniqueness => true
  validates :email, :format => { :with => /^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/, :message => 'must be valid' }
  validates :password, :confirmation => true
  validates :user_type, :presence => true, :inclusion => { :in => ['admin', 'user'] }
  #validates :company_id, :presence => true
  
  belongs_to :company
  
  attr_accessor :password_confirmation 
  attr_reader :password
  
  validate :password_must_be_present
  
  class << self 
    def authenticate(email, password)
      if user = find_by_email(email) 
        if user.hashed_password == encrypt_password(password, user.password_salt)
          user
        end 
      end
    end
    
    def authenticate_from_cookie(id, remember_key)
      if user = find(id) and user.remember_key == remember_key
        user
      end
    end
    
    def encrypt_password(password, password_salt) 
      Digest::SHA2.hexdigest(password + "cb093478n0f3smh" + password_salt) # Something random
    end 
  end
  
  # 'password' is a virtual attribute
  def password=(password) 
    @password = password
    
    if password.present? 
      generate_password_salt 
      
      self.hashed_password = self.class.encrypt_password(password, password_salt)
    end 
  end
  
  def admin?
    user_type == 'admin'
  end
  
  def remember_key
    Digest::SHA2.hexdigest(self.email + self.hashed_password)
  end

  private
    def password_must_be_present 
      errors.add(:password, "is missing") unless hashed_password.present?
    end

    def generate_password_salt 
      self.password_salt = self.object_id.to_s + rand.to_s
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize, :only => [:sign_up, :public_create]
  before_filter :require_admin, :except => [:sign_up, :public_create]
  before_filter :require_signed_out, :only => [:sign_up, :public_create]
  
  # GET /users
  # GET /users.xml
  def index
    not_found and return # Inactive for the moment
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    not_found and return # Inactive for the moment
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    not_found and return # Inactive for the moment
    if Company.all.empty?
      redirect_to new_company_path
    else
      @user = User.new
      
      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @user }
      end
    end
  end

  # GET /users/1/edit
  def edit
    not_found and return # Inactive for the moment
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    not_found and return # Inactive for the moment
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    not_found and return # Inactive for the moment
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    not_found and return # Inactive for the moment
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
  
  # GET /sign_up
  def sign_up
    @user = User.new
    @company = Company.new
  end
  
  # POST /sign_up
  def public_create
    @company = Company.new({:name => params[:company_name], :address => params[:company_address]})
    @user = User.new({
      :email => params[:email],
      :password => params[:password],
      :password_confirmation => params[:password_confirmation],
      :user_type => 'user' # Important that this is user
    })
    
    User.transaction do
      @user.save!
      @company.save!
      
      @user.company_id = @company.id
      @user.save!
    end
    
    respond_to do |format|
      format.html { redirect_to show_login_path, :notice => t('.sign_up_success') }
    end
    
  rescue ActiveRecord::RecordInvalid => invalid # Meaning something was not filled correctly in form
    respond_to do |format|
      format.html { render :action => :sign_up }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="grid_16">
      <% @user.errors.full_messages.each do |msg| %>
        <p class="error"><%= msg %></p>
      <% end %>
    </div>
    <div class="grid_16"><p><!-- SEPARATOR --></p></div>
  <% end %>

  <div class="grid_5">
      <%= f.label :email, t('.email') %>
      <%= f.text_field :email %>
  </div>
  
  <div class="grid_5">
      <%= f.label :password, t('.password') %>
      <%= f.password_field :password %>
  </div>
  
  <div class="grid_6">
      <%= f.label :password_confirmation, t('.password_confirmation') %>
      <%= f.password_field :password_confirmation %>
  </div>
  
  <div class="grid_16"><p><!-- SEPARATOR --></p></div>
  
  <div class="grid_8">
      <%= f.label :user_type, t('.user_type') %>
      <%= f.select :user_type, [[t('.admin'), 'admin'], [t('.user'), 'user']], :prompt => t('.select') %>
  </div>
  
  <div class="grid_8">
      <%= f.label :company_id, t('.company') %>
      <%= f.select :company_id, options_from_collection_for_select(Company.all, :id, :name), :prompt => t('.select') %>
  </div>
  
  <div class="grid_16"><p><!-- SEPARATOR --></p></div>
  
  <div class="grid_16">
    <p class="submit">
      <%= f.submit t('.save_user') %>
    </p>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>User Type</th>
      <th>Company</th>
      <th>Options</th>
    </tr>
  </thead>
  
  <!--<tfoot>
    <tr>
      <td colspan="5" class="pagination">
        <span class="active curved">1</span><a href="#" class="curved">2</a><a href="#" class="curved">3</a><a href="#" class="curved">4</a> ... <a href="#" class="curved">10 million</a>
      </td>
    </tr>
  </tfoot>-->
  
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.user_type %></td>
      <td><%= user.company_id %></td>
      <td><%= link_to 'Show', user %>
      <%= link_to 'Edit', edit_user_path(user) %>
      <%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="grid_16">
  <h2>New user</h2>
</div>

<%= render 'form' %>

<div class="grid_16">
  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>User Type:</b>
  <%= @user.user_type %>
</p>

<p>
  <b>Company:</b>
  <%= @user.company_id %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/sign_up.html.haml
.grid_16
  %h1= t('.sign_up')

- if @user.errors.any? or @company.errors.any?
  .grid_5 &nbsp;
  #error_explanation.grid_6
    - @user.errors.full_messages.each do |msg|
      %p.error= msg
    - @company.errors.full_messages.each do |msg|
      %p.error= msg
  = render :partial => "shared/separator"


= form_tag public_user_create_path do
  .grid_5 &nbsp;
  .grid_6
    = label_tag :email, t('.email_html')
    = email_field_tag :email, @user.email
    
  = render :partial => "shared/separator"
  
  .grid_5 &nbsp;
  .grid_6
    = label_tag :password, t('.password_html')
    = password_field_tag :password

  = render :partial => "shared/separator"
  
  .grid_5 &nbsp;
  .grid_6
    = label_tag :password_confirmation, t('.password_confirmation_html')
    = password_field_tag :password_confirmation

  = render :partial => "shared/separator"
  
  .grid_5 &nbsp;
  .grid_6
    = label_tag :company_name, t('.company_name_html')
    = text_field_tag :company_name, @company.name

  = render :partial => "shared/separator"
  
  .grid_5 &nbsp;
  .grid_6
    = label_tag :company_address, t('.company_address_html')
    = text_field_tag :company_address, @company.address

  = render :partial => "shared/separator"
  
  .grid_5 &nbsp;
  .grid_6
    = submit_tag t('.sign_up')
    = link_to t('.login'), show_login_path