config/routes.rb
Invoices::Application.routes.draw do
  controller :sessions do
    get "login", :action => :new, :as => :show_login
    post "login", :action => :create, :as => :do_login
    delete "logout", :action => :destroy, :as => :logout
  end

  resources :invoices
  
  resources :clients

  resources :companies

  resources :users
  controller :users do
    get "sign_up", :action => :sign_up, :as => :sign_up
    post "sign_up", :action => :public_create, :as => :public_user_create
  end

  root :to => "sessions#new"

end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, :presence => true
  
  has_many :users
  has_many :clients
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.xml
  def index
    not_found and return # Disable this view for now
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.xml
  def show
    not_found and return # Disable this view for now
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.xml
  def new
    not_found and return # Disable this view for now
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @company }
    end
  end

  # GET /companies/1/edit
  def edit
    not_found and return unless params[:id].to_i == current_user.company_id
    
    # Overwrite the company id if it was tampered with
    params[:id] = current_user.company_id
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.xml
  def create
    not_found and return # Disable this view for now
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to(@company, :notice => 'Company was successfully created.') }
        format.xml  { render :xml => @company, :status => :created, :location => @company }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.xml
  def update
    not_found and return unless params[:id].to_i == current_user.company_id
    
    # Overwrite the company id if it was tampered with
    params[:id] = current_user.company_id
    params[:company][:id] = current_user.company_id
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to(edit_company_path(@company), :notice => t('.company_updated')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.xml
  def destroy
    not_found and return # Disable manual company deletion
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to(companies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.haml
= form_for @company do |f|
  - if @company.errors.any?
    .grid_5 &nbsp;
    #error_explanation.grid_6
      - @company.errors.full_messages.each do |msg|
        %p.error= msg
    = render :partial => "shared/separator"
  
  .grid_5 &nbsp;
  .grid_6
    = f.label :name, t('.name')
    = f.text_field :name
  
  = render :partial => "shared/separator"
  
  .grid_5 &nbsp;
  .grid_6
    = f.label :address, t('.address')
    = f.text_field :address
  
  = render :partial => "shared/separator"
  
  .grid_5 &nbsp;
  .grid_6
    = f.submit t('.save')

app/views/companies/edit.html.haml
.grid_16
  %h1= t('.edit_company')

= render 'form'

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.address %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<p>
  <b>Address:</b>
  <%= @company.address %>
</p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>