config/routes.rb
Invoices::Application.routes.draw do
  controller :sessions do
    get "login", :action => :new, :as => :show_login
    post "login", :action => :create, :as => :do_login
    delete "logout", :action => :destroy, :as => :logout
  end

  resources :invoices
  
  resources :clients

  resources :companies

  resources :users
  controller :users do
    get "sign_up", :action => :sign_up, :as => :sign_up
    post "sign_up", :action => :public_create, :as => :public_user_create
  end

  root :to => "sessions#new"

end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= AppConfig.site_title
    = stylesheet_link_tag ['960', 'template', 'colour', 'messages'] # It was :all before
    = javascript_include_tag ['application', 'jquery', 'rails', 'jquery.tmpl.min.js']
    = csrf_meta_tag
    
    :javascript
      $(function(){
        $('#messages').slideDown();
        setTimeout(function(){
          $('#messages').slideUp();
        }, 30000); // 30 seconds
      });
  
  %body
    %h1#head
      = AppConfig.site_title
      - if signed_in?
        %span.right
          = t('.currently_logged_in_as')
          %strong= current_user.email
          %span
            (
            = link_to t('.not_you'), logout_path, :method => :delete, :confirm => t('.confirm_not_you')
            )
    
    %ul#navigation
      - if signed_in?
        %li=        link_to t('.new_invoice'), new_invoice_path, :class => 'active'
        %li=        link_to t('.invoices'), invoices_path
        %li=        link_to t('.clients'), clients_path
        %li.right=  link_to t('.logout'), logout_path, :method => :delete, :confirm => t('.confirm_logout')
        - if current_user.company
          %li.right=  link_to t('.edit_company'), edit_company_path(current_user.company)
        -#%li.right   Settings
      - else
        %li= link_to t('.login'), show_login_path
        %li= link_to t('.sign_up'), sign_up_path
    
    - if flash[:alert] || flash[:notice]
      #messages.container_16.clearfix{:style => "display: none;"}
        - if flash[:alert]
          %p.alert= flash[:alert]
        - elsif flash[:notice]
          %p.notice= flash[:notice]
    
    #content.container_16.clearfix= yield
    
    #foot
      Open Source Invoicing Powered by
      %strong Invoices